### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by alirezaafkar** [lingochamp/okdownload#106]
### OkDownload Version

v1.0.3

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
W/DownloadActivity: com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 200 with current offset 7994446
        at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:133)
        at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:170)
        at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.syncRunCall(DownloadDispatcher.java:362)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.execute(DownloadDispatcher.java:177)
        at com.liulishuo.okdownload.DownloadTask.execute(DownloadTask.java:516)
        at com.liulishuo.okdownload.DownloadContext$1.run(DownloadContext.java:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
You can check the log(there are require header and response header on the logcat).

This problem is expected because we required content with `range`, and this resource has been downloaded with the process(`7994446`bytes) and paused, now we request expected response code must be not `200`, it can be `206`.

Reference code: `DownloadStrategy#isServerCanceled`

**Comment by KwanTang324** [comment]
什么 意思啊，怎么解决这个问题
