### ISSUE TITLE
OkDownload 崩溃

### ISSUE THREAD

**Issue by jefshi** [lingochamp/okdownload#113]
### OkDownload Version

Current Latest Version

### Problem Describe

See Log

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
07-04 19:22:12.117 10309-10309/com.liulishuo.okdownload.sample W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
        at com.liulishuo.okdownload.OkDownloadProvider.$jacocoInit(OkDownloadProvider.java)
        at com.liulishuo.okdownload.OkDownloadProvider.<init>(OkDownloadProvider.java)
        at java.lang.Class.newInstance(Native Method)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5793)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5711)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
我调整下这块吧。

>  不过，不用担心，现在的情况也不会影响已发布的版本，因为这个只有在`debug` Type的时候开启，而发布的时候用的是Release Type。

**Comment by jefshi** [comment]
额，抱歉，发错 LogCat 了。崩溃的日志不是这个，尴尬了

**Comment by Jacksgong** [comment]
@jefshi 没关系，这个堆栈也是一个问题，只是在调试的时候会遇到，不过刚已经解决了。其他的crash，重新再开一个issue吧。
