### ISSUE TITLE
Socket Timeout

### ISSUE THREAD

**Issue by ChinhQT** [lingochamp/okdownload#123]
Hi all,

I often have this issue when download multiple files. Please help me how to fix them.

07-24 13:56:47.543 18026-18529/ht.nct W/System.err: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
07-24 13:56:47.544 18026-18529/ht.nct W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
        at java.io.InputStream.read(InputStream.java:101)
        at com.liulishuo.okdownload.core.interceptor.FetchDataInterceptor.interceptFetch(FetchDataInterceptor.java:62)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
07-24 13:56:47.545 18026-18529/ht.nct W/System.err:     at com.liulishuo.okdownload.core.download.DownloadChain.loopFetch(DownloadChain.java:228)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:108)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
07-24 13:56:47.546 18026-18529/ht.nct W/System.err:     at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:56)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:195)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-24 13:56:47.547 18026-18529/ht.nct W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-24 13:56:47.548 18026-18529/ht.nct W/System.err: Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)

**Comment by JianHaoZhangHB** [comment]
+1

**Comment by Jacksgong** [comment]
Socket timeout issue just about network situation, it isn't okdownload issue, if your network not allows multi-file download, please download file one-by-one use `DownloadSerialQueue` or handle by any way you want.

**Comment by ZDZN** [comment]
我在测试这个库和 FileDownloader 下载功能时同样出现这个异常，暂时只对这个库进行了分析，不清楚 FileDownloader 是不是也是因为这个原因。
我的场景是使用电脑模拟器，然后通过网络流量管理软件对模拟器进行限速。当下载任务根据下载库内置的下载策略进行分块下载或者进行 1 个以上的任务进行下载时，就会出现这个异常。
出现的原因应该是限速后只有一个连接读取正常，其他读取都超时了。所以如果是分块下载时，比如分成两个块就会在下载到一半时出现这个异常；如果是多个任务同时下载，每个任务都没有分块下载的情况下，一个任务是正常的，其他任务就会出现这个异常。
所以在这种网络环境下即使按照 @Jacksgong 所说的每个文件单独下载，但只要文件分块下载都会出现这个异常，所以如果有必要，还需要设置 DownloadTask.Builder.setConnectionCount(1) 才行。
后续我会找一个实际的低网速环境测试一下，看看是所以低网速环境都会出现这个问题，还是由于限速软件导致这个问题的出现

**Comment by qq2748** [comment]
我也遇到了这个问题, 下载特别大的文件(2GB)的时候 容易出现

**Comment by yarude** [comment]
2g文件同样，必现，而且开启一会就回出现
