### ISSUE TITLE
 java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by bubian** [lingochamp/okdownload#173]
### OkDownload Version

v1.0.4-SNAPSHOT

### Problem Describe

下载视频总是出现 java.net.SocketTimeoutException

### Log
10-08 16:11:12.541 27189-27189/net.medlinker.medlinker W/System.err: java.net.SocketTimeoutException
10-08 16:11:12.542 27189-27189/net.medlinker.medlinker W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:360)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:404)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
        at java.io.InputStream.read(InputStream.java:162)
        at com.liulishuo.okdownload.core.interceptor.FetchDataInterceptor.interceptFetch(FetchDataInterceptor.java:62)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.loopFetch(DownloadChain.java:228)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:108)
10-08 16:11:12.543 27189-27189/net.medlinker.medlinker W/System.err:     at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:56)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:195)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
看堆栈是读超时，这个属于网络问题(可能是服务端的网络问题也可能是本地的网络问题)。

## 解决方案

1. 优化本地网络与服务端网络
2. 看堆栈你使用的是okhttp3，这边可以通过`DownloadOkHttp3Connection.Factory`定制读超时时间，然后通过[wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component)中提到的方法传入
3. 你可以基于socket接口，自行定制网络协议相关进行深度优化，然后也是通过[wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component)中提到的方法传入
