### ISSUE TITLE
System.err: java.net.SocketException: recvfrom failed: ECONNRESET

### ISSUE THREAD

**Issue by bubian** [lingochamp/okdownload#174]
### OkDownload Version

v1.0.4-SNAPSHOT

### Problem Describe

下载视频总是出现 java.net.SocketTimeoutException

### Log
10-08 21:47:48.481 12669-12669/net.medlinker.medlinker W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at com.android.okio.Okio$2.read(Okio.java:113)
        at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
10-08 21:47:48.482 12669-12669/net.medlinker.medlinker W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
        at java.io.InputStream.read(InputStream.java:162)
        at com.liulishuo.okdownload.core.interceptor.FetchDataInterceptor.interceptFetch(FetchDataInterceptor.java:62)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.loopFetch(DownloadChain.java:228)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:108)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
10-08 21:47:48.483 12669-12669/net.medlinker.medlinker W/System.err:     at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:56)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:195)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
10-08 21:47:48.484 12669-12669/net.medlinker.medlinker W/System.err: Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
10-08 21:47:48.486 12669-12669/net.medlinker.medlinker W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java:185)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
    	... 22 more

**Comment by Jacksgong** [comment]
参考这里 #173
