### ISSUE TITLE
下载资源出现错误

### ISSUE THREAD

**Issue by Extendjack** [lingochamp/okdownload#176]
### OkDownload Version

v1.0.2

### Problem Describe
下载图片出现这个错误，但是能够从网页上访问

###log
com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 200 with current offset 315383
   at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:133)
   at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:170)
   at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
   at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.syncRunCall(DownloadDispatcher.java:369)
   at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.execute(DownloadDispatcher.java:183)
   at com.liulishuo.okdownload.DownloadTask.execute(DownloadTask.java:525)
   at com.liulishuo.okdownload.DownloadSerialQueue.run(DownloadSerialQueue.java:180)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:833)

**Comment by fujiandong1991** [comment]
我也遇到了同样的问题，文件可以通过chrome下载，但是用okdownload会报这个错，你有找到解决方法吗？

**Comment by rantianhua** [comment]
说明是在进行断点下载时，range 是从断点出请求下载，response code 应该是 206 而非 200 ，所以这是 server 的问题，请从 server 改正。请参考 [这里](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206)
