### ISSUE TITLE
SpeedCalculator.endTask() on a null object reference

### ISSUE THREAD

**Issue by imcloud** [lingochamp/okdownload#183]
### OkDownload Version

v1.0.4

### Problem Describe

应用第一次安装使用时空指针，再次下载就不会

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```Java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.findpiano.piano, PID: 28561
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.liulishuo.okdownload.SpeedCalculator.endTask()' on a null object reference
        at com.liulishuo.okdownload.core.listener.assist.Listener4SpeedAssistExtend.dispatchTaskEnd(Listener4SpeedAssistExtend.java:85)
        at com.liulishuo.okdownload.core.listener.assist.Listener4Assist.taskEnd(Listener4Assist.java:104)
        at com.liulishuo.okdownload.core.listener.DownloadListener4.taskEnd(DownloadListener4.java:116)
        at com.liulishuo.okdownload.core.dispatcher.CallbackDispatcher$DefaultTransmitListener$11.run(CallbackDispatcher.java:367)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by imcloud** [comment]
看到你最新代码修复了 我自己关掉吧
