### ISSUE TITLE
NPE when using listener4withspeed inside foreground service!

### ISSUE THREAD

**Issue by jpvs0101** [lingochamp/okdownload#186]
### OkDownload Version

 implementation 'com.liulishuo.okdownload:okdownload:1.0.4'
    implementation 'com.liulishuo.okdownload:sqlite:1.0.4'

### Problem Describe

I am calling it inside a foreground service..
 DownloadTask downloadTask = new DownloadTask.Builder(url, pathToSaveUri)
                .setFilename(fileName)
                .setPassIfAlreadyCompleted(false)
                .build();
 downloadTask.enqueue(new DownloadListener4WithSpeed() { blah blahs})

But it works normally when using listener1 inside service. 
Also all listeners works normally, when using inside Activity!

### Log

  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.liulishuo.okdownload.SpeedCalculator.endTask()' on a null object reference
        at com.liulishuo.okdownload.core.listener.assist.Listener4SpeedAssistExtend.dispatchTaskEnd(Listener4SpeedAssistExtend.java:85)
        at com.liulishuo.okdownload.core.listener.assist.Listener4Assist.taskEnd(Listener4Assist.java:104)
        at com.liulishuo.okdownload.core.listener.DownloadListener4.taskEnd(DownloadListener4.java:116)
        at com.liulishuo.okdownload.core.dispatcher.CallbackDispatcher$DefaultTransmitListener$11.run(CallbackDispatcher.java:367)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
Duplicate with #121
