### ISSUE TITLE
java.lang.NullPointerException:

### ISSUE THREAD

**Issue by YouJZ** [lingochamp/okdownload#187]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.liulishuo.okdownload.SpeedCalculator.endTask()' on a null object reference
        at com.liulishuo.okdownload.core.listener.assist.Listener4SpeedAssistExtend.dispatchTaskEnd(Listener4SpeedAssistExtend.java:85)
        at com.liulishuo.okdownload.core.listener.assist.Listener4Assist.taskEnd(Listener4Assist.java:104)
        at com.liulishuo.okdownload.core.listener.DownloadListener4.taskEnd(DownloadListener4.java:116)
        at com.liulishuo.okdownload.UnifiedListenerManager$1.taskEnd(UnifiedListenerManager.java:271)
        at com.liulishuo.okdownload.core.dispatcher.CallbackDispatcher$DefaultTransmitListener.taskEnd(CallbackDispatcher.java:371)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.inspectForConflict(DownloadDispatcher.java:492)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.inspectForConflict(DownloadDispatcher.java:427)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.inspectForConflict(DownloadDispatcher.java:420)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.enqueueLocked(DownloadDispatcher.java:153)
        at com.liulishuo.okdownload.core.dispatcher.DownloadDispatcher.enqueue(DownloadDispatcher.java:113)
        at com.liulishuo.okdownload.DownloadTask.enqueue(DownloadTask.java:515)
        at com.liulishuo.okdownload.UnifiedListenerManager.enqueueTaskWithUnifiedListener(UnifiedListenerManager.java:121)

**Comment by rantianhua** [comment]
This is duplicate with #121
