### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jingpeng** [lingochamp/okdownload#211]
### OkDownload Version

v1.0.5

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log
>>>backtrace<<<
java.lang.NullPointerException: Attempt to invoke interface method 'void com.liulishuo.okdownload.DownloadListener.taskStart(com.liulishuo.okdownload.DownloadTask)' on a null object reference
at com.liulishuo.okdownload.core.dispatcher.CallbackDispatcher$DefaultTransmitListener$1.run(CallbackDispatcher.java:198)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6402)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1000)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:890)

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by ALIMAXIMUM** [comment]
Its because you set listener to null.

**Comment by jingpeng** [comment]
I think download sdk should cover all of this kind of exception
