### ISSUE TITLE
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)

### ISSUE THREAD

**Issue by lyyzhn** [lingochamp/okdownload#216]
你好！我在使用OkDownload v1.0.5发布到线上的时候，发现报错采集系统采集到以下报错：
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1529)
	at com.liulishuo.okdownload.core.breakpoint.BreakpointSQLiteHelper.markFileClear(BreakpointSQLiteHelper.java:133)
	at com.liulishuo.okdownload.core.breakpoint.BreakpointStoreOnSQLite.markFileClear(BreakpointStoreOnSQLite.java:103)
	at com.liulishuo.okdownload.core.breakpoint.RemitStoreOnSQLite.markFileClear(RemitStoreOnSQLite.java:110)
	at com.liulishuo.okdownload.core.download.DownloadCall.inspectTaskEnd(DownloadCall.java:273)
	at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:251)
	at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

麻烦帮忙看一下，谢谢！

**Comment by 8888444422** [comment]
<dependency org='com.liulishuo.okdownload' name='okdownload' rev='1.0.5'>
  <artifact name='okdownload' ext='pom' />
</dependency>

**Comment by 8888444422** [comment]
jaidi905@gmail.com

**Comment by mysiga** [comment]
遇到同样问题+1

**Comment by HolenZhou** [comment]
v1.0.7 遇到同样问题
