### ISSUE TITLE
 multiDexEnabled true   导致   Unable to get provider com.liulishuo.okdownload.OkDownloadProvider

### ISSUE THREAD

**Issue by zzp880303** [lingochamp/okdownload#222]
java.lang.RuntimeException: Unable to get provider com.liulishuo.okdownload.OkDownloadProvider: java.lang.ClassNotFoundException: Didn't find class "com.liulishuo.okdownload.OkDownloadProvider" on path: DexPathList[[zip file "/data/app/www.xxxxx.com.xxxxxxreader-2.apk"],nativeLibraryDirectories=[/data/app-lib/www.xxxxx.reader-2, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.liulishuo.okdownload.OkDownloadProvider" on path: DexPathList[[zip file "/data/app/www.xxxxxx.com.xxxxxxxreader-2.apk"],nativeLibraryDirectories=[/data/app-lib/www.xxxxxxreader-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by a568690944** [comment]
楼主我也遇到这个问题你解决了吗
