### ISSUE TITLE
1.0.5 The current offset on block-info isn't update correct

### ISSUE THREAD

**Issue by HachikoDream** [lingochamp/okdownload#229]
看了之前的issues，有人反馈过这个问题，目前看这个问题仍然存在。
堆栈：
01-24 17:14:46.527 5181-5574/com.aliwork.fpark E/DGSLog: on download feature file failed
    java.io.IOException: The current offset on block-info isn't update correct, 0 != 969 on 0
        at com.liulishuo.okdownload.core.file.MultiPointOutputStream.inspectComplete(MultiPointOutputStream.java:263)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:123)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:57)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:195)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by gyurme-accedo** [comment]
I'm also seeing this as well, is this caused by a bug or when the server does not respond to the library?

**Comment by HachikoDream** [comment]
> I'm also seeing this as well, is this caused by a bug or when the server does not respond to the library?
I find the problem I met is that the file I want to download is empty

**Comment by blueskky** [comment]
+1

**Comment by rantianhua** [comment]
@HachikoDream 能给我一个示例 url 吗？或者一份完整的日志。

**Comment by rantianhua** [comment]
> I'm also seeing this as well, is this caused by a bug or when the server does not respond to the library?

Is this caused by a bug?
---
Maybe, but I need more info(like a whole log or a reproducible url) to verify it.

Is this caused by the server?
---
Maybe, if the server don't response correct stream length.
