### ISSUE TITLE
java.lang.IllegalArgumentException: Uri already provided filename!

### ISSUE THREAD

**Issue by AriesJiang** [lingochamp/okdownload#235]
### OkDownload Version

v1.0.5-SNAPSHOT

### Problem Describe

异步实例化DownloadTask的时候，抛出Uri already provided filename!异常

### Log

Fatal Exception: java.lang.IllegalArgumentException: Uri already provided filename!
       at com.liulishuo.okdownload.DownloadTask.(DownloadTask.java:165)
       at com.liulishuo.okdownload.DownloadTask$Builder.build(DownloadTask.java:916)

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by peter100u** [comment]
我也遇到了，你解决了吗 @AriesJiang
