### ISSUE TITLE
https Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by fengxing1234** [lingochamp/okdownload#261]
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at okhttp3.RealCall.execute(RealCall.java:92)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection.execute(DownloadOkHttp3Connection.java:57)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.liulishuo.okdownload.core.download.ConnectTrial.executeTrial(ConnectTrial.java:89)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:100)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:170)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
2019-05-13 15:17:40.722 30281-30281/com.picc.mcpbox W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err: 	... 27 more
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-13 15:17:40.723 30281-30281/com.picc.mcpbox W/System.err: 	... 39 more

**Comment by theyx** [comment]
你好，这个问题你解决了吗？
