### ISSUE TITLE
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by YuanTiger** [lingochamp/okdownload#332]
### OkDownload Version

v1.0.6

### Problem Describe

在将协议从HTTP切换到HTTPS时，本地选择跳过了HTTPS验证，跳过执行的代码如下：
```
try {
            //使用自己的OkhttpClient builder
            OkDownload.Builder builder = new OkDownload.Builder(App.context);

            DownloadOkHttp3Connection.Factory factory = new DownloadOkHttp3Connection.Factory();
            //跳过HTTPS验证
            final TrustManager[] trustAllCerts = new TrustManager[]{
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return new java.security.cert.X509Certificate[]{};
                        }
                    }
            };

            // Install the all-trusting trust manager
            final SSLContext sslContext;
            sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
            //okHttp初始化
            OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder()
                    .sslSocketFactory(sslContext.getSocketFactory())
                    .hostnameVerifier(new HostnameVerifier() {
                        @Override
                        public boolean verify(String s, SSLSession sslSession) {
                            return true;
                        }
                    })
                    .retryOnConnectionFailure(true);

            factory.setBuilder(okHttpBuilder);
            builder.connectionFactory(factory);
            OkDownload.setSingletonInstance(builder.build());
        } catch (Exception e) {
        }
```
其他地方没有改动的。

但是上线之后（目前线上还在使用HTTP协议），统计软件统计到了一个发生率很高的崩溃。请问一下这个崩溃有遇到过吗，该如何解决，感谢大大。

### Log
```
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
    at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
    at okhttp3.HttpUrl.get(HttpUrl.java:916)
    at okhttp3.Request$Builder.url(Request.java:165)
    at com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection.<init>(DownloadOkHttp3Connection.java:48)
    at com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection$Factory.create(DownloadOkHttp3Connection.java:146)
    at com.liulishuo.okdownload.core.download.ConnectTrial.executeTrial(ConnectTrial.java:75)
    at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:100)
    at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:180)
    at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
这个异常是 OkHttp 抛出的，具体可见：
```
Builder parse(@Nullable HttpUrl base, String input) {
      ...
      if (schemeDelimiterOffset != -1) {
        if (input.regionMatches(true, pos, "https:", 0, 6)) {
          this.scheme = "https";
          pos += "https:".length();
        } else if (input.regionMatches(true, pos, "http:", 0, 5)) {
          this.scheme = "http";
          pos += "http:".length();
        } else {
          throw new IllegalArgumentException("Expected URL scheme 'http' or 'https' but was '"
              + input.substring(0, schemeDelimiterOffset) + "'");
        }
      } else if (base != null) {
        this.scheme = base.scheme;
      } else {
        throw new IllegalArgumentException(
            "Expected URL scheme 'http' or 'https' but no colon was found");
      }
      ...
      return this;
    }
```
应该是你的 URL 有问题。
不过 OkDownload 应该 Catch 住这个异常，避免崩溃。

**Comment by rantianhua** [comment]
会在 1.0.7 版本 Catch 住这个异常并通过 error 回调抛出。

**Comment by YuanTiger** [comment]
是的，这段OkHttp的源码我也看到了，但是具体哪个URL有问题，我这边无法复现。

再次感谢作者大大的开源，更新之后可以@我一下，嘿嘿。

**Comment by zhangzhen123** [comment]
这个异常抓取了吗？为什么我在1.0.7还是崩掉了  这种问题出现在一个4K星的项目上 感觉不应该啊 还是说我使用的方式不对 需要哪里显示声明错误才不会抛出？
