### ISSUE TITLE
下载指定文件时总是下到一半就出错

### ISSUE THREAD

**Issue by Mystery406** [lingochamp/okdownload#343]
### OkDownload Version

v1.0.6

### Problem Describe

把sample里的SingleActivity的下载url改成“https://duolunstorage.duolunxc.com/ddjdQuest/201912/20191205152800.zip“  
总是下载一半出错

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

com.liulishuo.okdownload.sample E/SingleActivity: download error
    okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
        at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:436)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
        at java.io.InputStream.read(InputStream.java:101)
        at com.liulishuo.okdownload.core.interceptor.FetchDataInterceptor.interceptFetch(FetchDataInterceptor.java:62)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.loopFetch(DownloadChain.java:228)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:108)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:57)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:195)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
走了 HTTP 2 ，这个问题你可以在 okhttp 的 issue 里面去找找看。如果你想快速解决，可以强制使用 HTTP/1.1 ，设置可参考 https://www.cnblogs.com/myhalo/p/6811472.html 。
