### ISSUE TITLE
下载失败，查看log是创建文件没有权限

### ISSUE THREAD

**Issue by ZhangHui0608** [lingochamp/okdownload#364]
01-03 08:56:07.691 32248-32248/com.backaudio.upgrade W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
01-03 08:56:07.693 32248-32248/com.backaudio.upgrade W/System.err:     at java.io.File.createNewFile(File.java:948)
01-03 08:56:07.693 32248-32248/com.backaudio.upgrade W/System.err:     at com.liulishuo.okdownload.core.file.MultiPointOutputStream.outputStream(MultiPointOutputStream.java:514)
01-03 08:56:07.693 32248-32248/com.backaudio.upgrade W/System.err:     at c

**Comment by ZhangHui0608** [comment]
是因为我应用中加了android:sharedUserId="android.uid.system"，
去掉以后可以成功下载，但我应用中又想加这个
