### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hi-dhl** [lingochamp/okdownload#367]
v1.0.6

## Problem Describe

![image](https://user-images.githubusercontent.com/16751752/72123648-e352f180-339c-11ea-97c1-6010b1e9756f.png)

01-09 15:08:08.781 14743 19215 E AndroidRuntime: java.lang.c: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
01-09 15:08:08.781 14743 19215 E AndroidRuntime:  at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:149)
01-09 15:08:08.781 14743 19215 E AndroidRuntime:  at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)

源码DownloadTask里面的url是final 并且不为空， 在我的代码里面，url 也是final 并且不为空，为什么这里会出现，空指针异常，不是必现，50次可能会出现一次，初始化代码如下：

![image](https://user-images.githubusercontent.com/16751752/72124067-658fe580-339e-11ea-9cde-3c13a1be54a0.png)

**Comment by EMIN3M1986** [comment]
```
if(!TextUtils.isEmpty(task.getURL())) {
...
}
```
