### ISSUE TITLE
BlockInfoRow.toInfo:  Caused by: java.lang.IllegalArgumentException  

### ISSUE THREAD

**Issue by nukc** [lingochamp/okdownload#394]
### OkDownload Version

v1.0.7

### Problem Describe

设备：三星 Android 10
测试文件下载链接：http://mirrors.nju.edu.cn/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-dvd1.iso

```kotlin
        OkDownload.setSingletonInstance(
            OkDownload.Builder(context)
                .downloadStore(BreakpointStoreOnSQLite(context))
                .build()
        )
```
下载文件未完成按取消，杀进程，重新打开就报错了。看了后发现是这里 contentLength < 0 且不是 -1
```java
        if (startOffset < 0 || (contentLength < 0 && contentLength != CHUNKED_CONTENT_LENGTH)
                || currentOffset < 0) {
            throw new IllegalArgumentException();
        }
```
清除应用数据然后继续测试，下载按取消，查看数据库表 ``block``，表中该对应 id 的 ``contentLength`` 为 8231321600。
杀进程，重新打开应用，``BreakpointSQLiteHelper.loadToCache`` 获取该 id 的 contentLength 却是负数 -358612992

![image](https://user-images.githubusercontent.com/9924409/85095472-0e7f1e00-b224-11ea-8f5b-42cc3bcfeab8.png)
![image](https://user-images.githubusercontent.com/9924409/85095513-2ce51980-b224-11ea-9e8e-51b4a0d73d41.png)

### Log
```java
Caused by: java.lang.IllegalArgumentException
        at com.liulishuo.okdownload.core.breakpoint.BlockInfo.<init>(BlockInfo.java:39)
        at com.liulishuo.okdownload.core.breakpoint.BlockInfoRow.toInfo(BlockInfoRow.java:57)
        at com.liulishuo.okdownload.core.breakpoint.BreakpointSQLiteHelper.loadToCache(BreakpointSQLiteHelper.java:183)
        at com.liulishuo.okdownload.core.breakpoint.BreakpointStoreOnSQLite.<init>(BreakpointStoreOnSQLite.java:42)
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by nukc** [comment]
```java
    public BlockInfoRow(Cursor cursor) {
        this.breakpointId = cursor.getInt(cursor.getColumnIndex(HOST_ID));
        this.startOffset = cursor.getInt(cursor.getColumnIndex(START_OFFSET));
        this.contentLength = cursor.getInt(cursor.getColumnIndex(CONTENT_LENGTH));
        this.currentOffset = cursor.getInt(cursor.getColumnIndex(CURRENT_OFFSET));
    }
```
getLong 吧

**Comment by kutukoff** [comment]
same issue!
