### ISSUE TITLE
sample crash

### ISSUE THREAD

**Issue by huxian99** [lingochamp/okdownload#4]
In sample project, when I click 'start' button on Single Download page, it does't work, and then I click 'cancel' button, but the project crash.

01-09 11:14:13.819 12251-12251/com.liulishuo.okdownload.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.liulishuo.okdownload.sample, PID: 12251
                                                                                 java.lang.NullPointerException: Attempt to read from field 'com.liulishuo.okdownload.core.breakpoint.BreakpointInfo com.liulishuo.okdownload.core.listener.assist.Listener4Assist$Listener4Model.info' on a null object reference
                                                                                     at com.liulishuo.okdownload.core.listener.assist.Listener4Assist.taskEnd(Listener4Assist.java:127)
                                                                                     at com.liulishuo.okdownload.core.listener.DownloadListener4.taskEnd(DownloadListener4.java:87)
                                                                                     at com.liulishuo.okdownload.core.dispatcher.CallbackDispatcher$1$10.run(CallbackDispatcher.java:191)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by Jacksgong** [comment]
Thanks it has been fixed in the lastest master branch.
