### ISSUE TITLE
SocketTimeoutException happen

### ISSUE THREAD

**Issue by yanglichuan** [lingochamp/okdownload#446]
最新代码：拼房暂停 启动 删除   
会 java.net.SocketTimeoutException: timeout

**Comment by yanglichuan** [comment]
E/SingleActivity: download error
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
        at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:146)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:125)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection.execute(DownloadOkHttp3Connection.java:58)
        at com.liulishuo.okdownload.core.download.ConnectTrial.executeTrial(ConnectTrial.java:89)
        at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:100)
        at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:180)
        at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by jingzhanwu** [comment]
最后怎么解决这个问题的

**Comment by ZackLee** [comment]
同样遇到类似问题，老哥有解决或者定位到问题是哪里导致的吗？

**Comment by ZackLee** [comment]
你用的okhttp3 版本是多少？我这边低于OkHttp 4.9 暂停 启动  几次，就会报timetout, 把OkHttp 升级到4.9 可以解决这个问题。
