### ISSUE TITLE
从FileDownloader 迁移到 OkDownload崩溃

### ISSUE THREAD

**Issue by pcsyp** [lingochamp/okdownload#468]
// implementation "com.liulishuo.filedownloader:library:1.7.7"
    implementation "com.liulishuo.okdownload:okdownload:1.0.7"
    implementation "com.liulishuo.okdownload:filedownloader:1.0.7"
    implementation "com.liulishuo.okdownload:sqlite:1.0.7"

运行后  
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.liulishuo.filedownloader.FileDownloadMonitor$IMonitor com.liulishuo.filedownloader.FileDownloadMonitor$DownloadMonitorAdapter.callbackMonitor' on a null object reference
        at com.liulishuo.filedownloader.FileDownloadMonitor.getMonitor(FileDownloadMonitor.java:50)
        at com.xxx.xxxx.db.TasksManager.init(TasksManager.java:82)

**Comment by qinweiforandroid** [comment]
我也做了一个类似的工具，可以参考一下
https://github.com/qinweiforandroid/QDownload
