### ISSUE TITLE
Resume failed because of RESPONSE_ETAG_CHANGED

### ISSUE THREAD

**Issue by nikunjparadvaAB** [lingochamp/okdownload#488]
### OkDownload Version

v1.0.7 

### Problem Describe

I have face this Downloading issue with this url :- https://filedn.eu/lT5MTrPP9oSbL8W0tjWsva5/3d%20wallpaper/mastercollection/52_mini.zip

I just replace URL in this Sample's SingleActivity.kt and run this Project and I got this error. I pasted logcat below Please check and Help me out to solve this

### Log

```
14026-14026/com.liulishuo.okdownload.sample D/DownloadDispatcher: enqueueLocked for single task: com.liulishuo.okdownload.DownloadTask@16fcd433@1@https://filedn.eu/lT5MTrPP9oSbL8W0tjWsva5/3d%20wallpaper/mastercollection/52_mini.zip@/storage/emulated/0/Android/data/com.liulishuo.okdownload.sample/cache/single-test
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: taskStart: 1
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start trial task(1) {if-match=["fd56aff1df79af70eb509ed43d78253d0cc3724e"], range=[bytes=0-0]}
14026-14081/com.liulishuo.okdownload.sample D/RemitSyncExecutor: sync info with id: 1
14026-14760/com.liulishuo.okdownload.sample D/ConnectTrial: task[1] redirect location: null
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish trial task(1) code[206]{accept-ranges=[bytes], connection=[keep-alive], content-length=[1], content-range=[bytes 0-0/250697], content-transfer-encoding=[binary], content-type=[application/zip], date=[Thu, 18 Aug 2022 09:09:15 +0000], etag=["fd56aff1df79af70eb509ed43d78253d0cc3724e"], expires=[Thu, 18 Aug 2022 15:09:15 +0000], keep-alive=[timeout=30], last-modified=[Tue, 16 Aug 2022 06:50:26 +0000], server=[CloudHTTPd v1.1]}
14026-14760/com.liulishuo.okdownload.sample D/DownloadDispatcher: is file conflict after run: 1
14026-14760/com.liulishuo.okdownload.sample D/DownloadCall: breakpoint invalid: download from beginning because of local check is dirty 1 fileExist[false] infoRight[true] outputStreamSupport[true] com.liulishuo.okdownload.core.download.BreakpointLocalCheck@7ecdfc9
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: downloadFromBeginning: 1
14026-14766/com.liulishuo.okdownload.sample D/DownloadChain: create connection on url: https://filedn.eu/lT5MTrPP9oSbL8W0tjWsva5/3d%20wallpaper/mastercollection/52_mini.zip
14026-14766/com.liulishuo.okdownload.sample D/HeaderInterceptor: AssembleHeaderRange (1) block(0) downloadFrom(0) currentOffset(0)
14026-14766/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start connection task(1) block(0) {if-match=["fd56aff1df79af70eb509ed43d78253d0cc3724e"], range=[bytes=0-250696], user-agent=[OkDownload/1.0.8-SNAPSHOT]}
14026-14766/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish connection task(1) block(0) code[206]{accept-ranges=[bytes], connection=[keep-alive], content-length=[250697], content-range=[bytes 0-250696/250697], content-transfer-encoding=[binary], content-type=[application/zip], date=[Thu, 18 Aug 2022 09:09:15 +0000], etag=["5d34b6ff0e89d681158ea06fac95d1835cb9ade0"], expires=[Thu, 18 Aug 2022 15:09:15 +0000], keep-alive=[timeout=30], last-modified=[Tue, 16 Aug 2022 06:50:26 +0000], server=[CloudHTTPd v1.1]}
14026-14081/com.liulishuo.okdownload.sample D/RemitSyncExecutor: remove info 1
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start trial task(1) {range=[bytes=0-0]}
14026-14767/com.liulishuo.okdownload.sample D/DownloadChain: release connection com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection@cdaaf85 task[1] block[0]
14026-14760/com.liulishuo.okdownload.sample D/ConnectTrial: task[1] redirect location: null
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish trial task(1) code[206]{accept-ranges=[bytes], connection=[keep-alive], content-length=[1], content-range=[bytes 0-0/250697], content-transfer-encoding=[binary], content-type=[application/zip], date=[Thu, 18 Aug 2022 09:09:16 +0000], etag=["fd56aff1df79af70eb509ed43d78253d0cc3724e"], expires=[Thu, 18 Aug 2022 15:09:15 +0000], keep-alive=[timeout=30], last-modified=[Tue, 16 Aug 2022 06:50:26 +0000], server=[CloudHTTPd v1.1]}
14026-14760/com.liulishuo.okdownload.sample D/DownloadDispatcher: is file conflict after run: 1
14026-14760/com.liulishuo.okdownload.sample D/DownloadCall: breakpoint invalid: download from beginning because of local check is dirty 1 fileExist[false] infoRight[false] outputStreamSupport[true] com.liulishuo.okdownload.core.download.BreakpointLocalCheck@7571da
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: downloadFromBeginning: 1
14026-14766/com.liulishuo.okdownload.sample D/DownloadChain: create connection on url: https://filedn.eu/lT5MTrPP9oSbL8W0tjWsva5/3d%20wallpaper/mastercollection/52_mini.zip
14026-14766/com.liulishuo.okdownload.sample D/HeaderInterceptor: AssembleHeaderRange (1) block(0) downloadFrom(0) currentOffset(0)
14026-14766/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start connection task(1) block(0) {if-match=["fd56aff1df79af70eb509ed43d78253d0cc3724e"], range=[bytes=0-250696], user-agent=[OkDownload/1.0.8-SNAPSHOT]}
14026-14766/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish connection task(1) block(0) code[206]{accept-ranges=[bytes], connection=[keep-alive], content-length=[250697], content-range=[bytes 0-250696/250697], content-transfer-encoding=[binary], content-type=[application/zip], date=[Thu, 18 Aug 2022 09:09:16 +0000], etag=["5d34b6ff0e89d681158ea06fac95d1835cb9ade0"], expires=[Thu, 18 Aug 2022 15:09:15 +0000], keep-alive=[timeout=30], last-modified=[Tue, 16 Aug 2022 06:50:26 +0000], server=[CloudHTTPd v1.1]}
14026-14760/com.liulishuo.okdownload.sample D/CallbackDispatcher: taskEnd: 1 ERROR com.liulishuo.okdownload.core.exception.ResumeFailedException: Resume failed because of RESPONSE_ETAG_CHANGED
14026-14760/com.liulishuo.okdownload.sample D/DownloadCall: call is finished 1
14026-14026/com.liulishuo.okdownload.sample E/SingleActivity: download error
    com.liulishuo.okdownload.core.exception.ResumeFailedException: Resume failed because of RESPONSE_ETAG_CHANGED
        at com.liulishuo.okdownload.core.download.DownloadStrategy$ResumeAvailableResponseCheck.inspect(DownloadStrategy.java:297)
        at com.liulishuo.okdownload.core.interceptor.connect.HeaderInterceptor.interceptConnect(HeaderInterceptor.java:103)
        at com.liulishuo.okdownload.core.download.DownloadChain.processConnect(DownloadChain.java:215)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptConnect(BreakpointInterceptor.java:48)
        at com.liulishuo.okdownload.core.download.DownloadChain.processConnect(DownloadChain.java:215)
        at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptConnect(RetryInterceptor.java:40)
        at com.liulishuo.okdownload.core.download.DownloadChain.processConnect(DownloadChain.java:215)
        at com.liulishuo.okdownload.core.download.DownloadChain.start(DownloadChain.java:180)
        at com.liulishuo.okdownload.core.download.DownloadChain.run(DownloadChain.java:247)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
14026-14081/com.liulishuo.okdownload.sample D/RemitSyncExecutor: sync info with id: 1
14026-14081/com.liulishuo.okdownload.sample D/RemitSyncExecutor: remove free bunch id 1
14026-14767/com.liulishuo.okdownload.sample D/DownloadChain: release connection com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection@a78ece8 task[1] block[0]

```

**Comment by TarunSainiZO** [comment]
@nikunjparadvaAB, have you solved this issue?
