### ISSUE TITLE
DownloadTask.build导致的context == null 错误

### ISSUE THREAD

**Issue by Scorpiolol** [lingochamp/okdownload#95]
通过AIDL相关操作时
DownloadTask task = new DownloadTask.Builder(url, savePath, fileName)
                .setPassIfAlreadyCompleted(false)
                .build();
这行代码会报错
错误log为

2018-06-10 18:55:07.109 2124-2124/zcy.developer.downloadsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: zcy.developer.downloadsample, PID: 2124
    java.lang.IllegalStateException: context == null
        at android.os.Parcel.readException(Parcel.java:1692)
        at android.os.Parcel.readException(Parcel.java:1637)
        at zcy.developer.download_module.IDownloadConn$Stub$Proxy.onRegister(IDownloadConn.java:91)
        at zcy.developer.downloadsample.MainActivity$1.onServiceConnected(MainActivity.java:57)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Jacksgong** [comment]
通过堆栈获知并不是okdownload的问题。

**Comment by Heber-xu** [comment]
参考 https://github.com/lingochamp/okdownload/issues/253 的方法是否能解决。

**Comment by wangrunxiang** [comment]
@Jacksgong 所以问题是在哪里？
